// ─────────────────────────────────────────────────────────────
// Schema: conversations & messages — WhatsApp chat threads
// ─────────────────────────────────────────────────────────────

import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  pgEnum,
  boolean,
  jsonb,
} from "drizzle-orm/pg-core";
import { companies } from "./companies";
import { contacts } from "./contacts";
import { users } from "./users";

export const conversationStatusEnum = pgEnum("conversation_status", [
  "open",       // Active — AI or agent is handling it
  "bot",        // AI is handling autonomously
  "agent",      // Assigned to a human agent
  "resolved",   // Closed
  "waiting",    // Waiting for client reply (follow-up pending)
]);

export const messageRoleEnum = pgEnum("message_role", [
  "user",       // Message from the WhatsApp contact
  "assistant",  // Message generated by the AI
  "agent",      // Message sent manually by a human agent
  "system",     // Internal system note (not sent to client)
]);

// ── conversations ────────────────────────────────────────────

export const conversations = pgTable("conversations", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id")
    .notNull()
    .references(() => companies.id, { onDelete: "cascade" }),
  contactId: uuid("contact_id")
    .notNull()
    .references(() => contacts.id, { onDelete: "cascade" }),

  // WhatsApp thread identifier (phone number or WA chat id)
  whatsappChatId: varchar("whatsapp_chat_id", { length: 100 }).notNull(),

  status: conversationStatusEnum("status").notNull().default("bot"),
  assignedTo: uuid("assigned_to").references(() => users.id, { onDelete: "set null" }),

  // AI context window stored for continuity (last N messages summary)
  aiContextSummary: text("ai_context_summary"),

  lastMessageAt: timestamp("last_message_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ── messages ─────────────────────────────────────────────────

export const messages = pgTable("messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),
  companyId: uuid("company_id")
    .notNull()
    .references(() => companies.id, { onDelete: "cascade" }),

  role: messageRoleEnum("role").notNull(),
  body: text("body").notNull(),

  // WhatsApp message ID (for delivery tracking)
  waMessageId: varchar("wa_message_id", { length: 255 }),

  // Media attachment if any
  mediaUrl: varchar("media_url", { length: 1024 }),
  mediaType: varchar("media_type", { length: 50 }),

  // AI metadata (tool calls, intent detected, etc.)
  aiMetadata: jsonb("ai_metadata").$type<Record<string, unknown>>(),

  isRead: boolean("is_read").notNull().default(false),
  sentAt: timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
});
